from experta import Fact
from se_diagnostico_respiratorio import EvaluacionClinica
from se_diagnostico_respiratorio import Sintomas, Examenes, FactoresRiesgo

motor = EvaluacionClinica()
motor.reset()
motor.declare(Sintomas(oxg=91))
#02 motor.declare(Sintomas(fiebre=39), Sintomas(tos='tos productiva'), Examenes(pcr=50))
#03 motor.declare(Examenes(radiografia='condensación'))
#04 motor.declare(Sintomas(tos='tos seca'), Sintomas(fiebre=37), Examenes(pcr=9))
#05 motor.declare(Sintomas(frec_resp=25), FactoresRiesgo(edad=25))
#06 motor.declare(Sintomas(dolor_pecho='sí'), Sintomas(tos='tos productiva'))
#07 motor.declare(FactoresRiesgo(edad=65), FactoresRiesgo(comorbilidad=1))
#08 motor.declare(Examenes(radiografia='infiltrado'), Examenes(pcr=30))
#09 motor.declare(FactoresRiesgo(expo_reciente='sí'), Sintomas(fiebre=38))
#10 motor.declare(Sintomas(oxg=93))
#11 motor.declare(FactoresRiesgo(comorbilidad=2), Sintomas(fiebre=38))
#12 motor.declare(Examenes(pcr=15), Sintomas(tos='tos productiva'))
#13 motor.declare(Examenes(radiografia='normal'), Sintomas(fiebre=37))
motor.declare(Sintomas(frec_resp=30))
#15 motor.declare(Sintomas(dolor_pecho='sí'), Sintomas(oxg=94))
#16 motor.declare(FactoresRiesgo(edad=11))
motor.declare(Examenes(pcr=100))
#18 motor.declare(Sintomas(duracion_tos=22))
#19 motor.declare(Sintomas(fiebre=38), Examenes(pcr=15))
#20 motor.declare(FactoresRiesgo(expo_reciente='brote comunitario'))
#21 motor.declare(Examenes(radiografia='empeora'), Examenes(radiografia_tiempo=55))
#22 motor.declare(Sintomas(oxg=96), Sintomas(sintomas='leves'))
#23 motor.declare(Sintomas(tos='tos espesa'), Sintomas(fiebre=38.5))
#24 motor.declare(FactoresRiesgo(comorbilidad=0), FactoresRiesgo(edad=45), Examenes(pcr=9))
motor.declare(Sintomas(dolor_pecho='severo'))
#26 motor.declare(Sintomas(frec_resp_cambio='normal'), Sintomas(frec_resp_tiempo=36))
#27 motor.declare(Examenes(pcr_aumento=51), Examenes(pcr_tiempo_aumento=45))
#28 motor.declare(Sintomas(duracion_fiebre=6))
#29 motor.declare(FactoresRiesgo(expo_reciente='no'), Examenes(radiografia='normal'))
motor.declare(Fact(activar=1))
motor.run()